In [1]:
import yfinance as yf
tickers=['AMZN','GOOG','TSLA']
ohlcv_data={}
for ticker in tickers:
    temp=yf.download(ticker,period='1mo',interval='5m')
    temp.dropna(how='any',inplace=True)
    ohlcv_data[ticker]=temp

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [2]:
def Boll_band(DF,n=14):
    df=DF.copy()
    df['MB']=df['Adj Close'].rolling(n).mean()
    df["UB"]=df['MB'] + 2*df['Adj Close'].rolling(n).std(ddof=0) 
    df["LB"]=df['MB'] - 2*df['Adj Close'].rolling(n).std(ddof=0) 
    df['BB_Width']=df['UB'] - df['LB']
    return df[['MB','UB','LB','BB_Width']]

In [3]:
for ticker in ohlcv_data:
    ohlcv_data[ticker][['MB','UB','LB','BB_Width']]=Boll_band(ohlcv_data[ticker])

In [4]:
ohlcv_data['AMZN']

,Open,High,Low,Close,Adj Close,Volume,MB,UB,LB,BB_Width
Datetime,,,,,,,,,,
2023-07-10 09:30:00-04:00,129.070007,129.279999,127.970001,128.070496,128.070496,4251637,NaN,NaN,NaN,NaN
2023-07-10 09:35:00-04:00,128.070007,128.299500,127.489998,127.589996,127.589996,2318469,NaN,NaN,NaN,NaN
2023-07-10 09:40:00-04:00,127.589996,128.050003,127.510002,127.555000,127.555000,1731427,NaN,NaN,NaN,NaN
2023-07-10 09:45:00-04:00,127.529999,127.729301,126.809998,126.910004,126.910004,2061225,NaN,NaN,NaN,NaN
2023-07-10 09:50:00-04:00,126.919998,127.000000,126.330002,126.629997,126.629997,1806138,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2023-08-08 15:35:00-04:00,139.550003,139.570007,139.455002,139.520004,139.520004,325998,139.552855,139.753558,139.352152,0.401406
2023-08-08 15:40:00-04:00,139.509995,139.789902,139.490005,139.619995,139.619995,657279,139.550713,139.747830,139.353595,0.394235
2023-08-08 15:45:00-04:00,139.619995,139.979996,139.589996,139.901794,139.901794,846951,139.577269,139.843968,139.310570,0.533398
2023-08-08 15:50:00-04:00,139.899994,140.130005,139.759995,139.832199,139.832199,1044726,139.601355,139.893660,139.309051,0.584610
2023-08-08 15:55:00-04:00,139.830002,140.050003,139.764999,139.899994,139.899994,1709852,139.629569,139.953740,139.305397,0.648343