In [50]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

#Function that takes in the stock ticker as a string and gives the income statement data from YahooFinance

def income_statement_getter(ticker):
    
    income_statement_dict={}

    url='https://finance.yahoo.com/quote/{}/financials?p={}'.format(ticker,ticker)
    income_statement={}
    table_title={}

    headers = {'User-Agent' : 'Safari/19616.1.24.11.3'}
    page=requests.get(url,headers=headers)
    page_content=page.content
    soup=BeautifulSoup(page_content,'html.parser')
    tabl=soup.find_all('div',{'class':'M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)'})
    for t in tabl:
        heading=soup.find_all('div',{'class':'D(tbr) C($primaryColor)'})
        for top_row in heading:
            table_title[top_row.get_text(separator="|").split("|")[0]] = top_row.get_text(separator="|").split("|")[1:]
        rows=soup.find_all('div',{'class' : "D(tbr) fi-row Bgc($hoverBgColor):h"})
        for row in rows:
            income_statement[row.get_text(separator="|").split("|")[0]]=row.get_text(separator="|").split("|")[1:]
    temp=pd.DataFrame(income_statement).T
    temp.columns=table_title['Breakdown']
    income_statement_dict[ticker]=temp
    
    #Converting string objects to numerical values
    
    for col in income_statement_dict[ticker].columns:
        income_statement_dict[ticker][col]=income_statement_dict[ticker][col].str.replace(',|-','')
        income_statement_dict[ticker][col]=pd.to_numeric(income_statement_dict[ticker][col],errors='coerce')
    
    return(income_statement_dict[ticker])

#Function that takes in the stock ticker as a string and gives the balance sheet data from YahooFinance

def balance_sheet_getter(ticker):  
    
    balance_sheet_dict={}
    
    url='https://finance.yahoo.com/quote/{}/balance-sheet?p={}'.format(ticker,ticker)
    balance_sheet={}
    table_title={}
    
    headers = {'User-Agent' : 'Safari/19616.1.24.11.3'}
    page=requests.get(url,headers=headers)
    page_content=page.content
    soup=BeautifulSoup(page_content,'html.parser')
    tabl=soup.find_all('div',{'class':'M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)'})
    for t in tabl:
        heading=soup.find_all('div',{'class':'D(tbr) C($primaryColor)'})
        for top_row in heading:
            table_title[top_row.get_text(separator="|").split("|")[0]] = top_row.get_text(separator="|").split("|")[1:]
        rows=soup.find_all('div',{'class' : "D(tbr) fi-row Bgc($hoverBgColor):h"})
        for row in rows:
            balance_sheet[row.get_text(separator="|").split("|")[0]]=row.get_text(separator="|").split("|")[1:]
    temp=pd.DataFrame(balance_sheet).T
    temp.columns=table_title['Breakdown']
    balance_sheet_dict[ticker]=temp
    
    #Converting string objects to numerical values
    
    for col in balance_sheet_dict[ticker].columns:
        balance_sheet_dict[ticker][col]=balance_sheet_dict[ticker][col].str.replace(',|-','')
        balance_sheet_dict[ticker][col]=pd.to_numeric(balance_sheet_dict[ticker][col],errors='coerce')
    
    return(balance_sheet_dict[ticker])

#Function that takes in the stock ticker as a string and gives the cashflow data from YahooFinance
    
def cashflow_statement_getter(ticker):
    
    cashflow_dict={}
    
    url='https://finance.yahoo.com/quote/{}/cash-flow?p={}'.format(ticker,ticker)
    cashflow={}
    table_title={}
    
    headers = {'User-Agent' : 'Safari/19616.1.24.11.3'}
    page=requests.get(url,headers=headers)
    page_content=page.content
    soup=BeautifulSoup(page_content,'html.parser')
    tabl=soup.find_all('div',{'class':'M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)'})
    for t in tabl:
        heading=soup.find_all('div',{'class':'D(tbr) C($primaryColor)'})
        for top_row in heading:
            table_title[top_row.get_text(separator="|").split("|")[0]] = top_row.get_text(separator="|").split("|")[1:]
        rows=soup.find_all('div',{'class' : "D(tbr) fi-row Bgc($hoverBgColor):h"})
        for row in rows:
            cashflow[row.get_text(separator="|").split("|")[0]]=row.get_text(separator="|").split("|")[1:]
    temp=pd.DataFrame(cashflow).T
    temp.columns=table_title['Breakdown']
    cashflow_dict[ticker]=temp
    
    #Converting all the string values to numeric values
   
    for col in cashflow_dict[ticker].columns:
        cashflow_dict[ticker][col]=cashflow_dict[ticker][col].str.replace(',|-','')
        cashflow_dict[ticker][col]=pd.to_numeric(cashflow_dict[ticker][col],errors='coerce')
    
    return(cashflow_dict[ticker])

In [54]:
cashflow_statement_getter('ITC.BO')

,ttm,3/31/2023,3/31/2022,3/31/2021,3/31/2020
Operating Cash Flow,188775500,188775500,157755100,125270900,146896600
Investing Cash Flow,57322900,57322900,22384900,56829100,61740200
Financing Cash Flow,130060300,130060300,135805000,186338300,81814800
End Cash Position,4059100,4059100,2666800,3101600,6770400
Capital Expenditure,27429900,27429900,21416400,18366400,24411500
Issuance of Capital Stock,24773900,24773900,2918200,2906500,6253000
Repayment of Debt,7300,7300,3500,22800,34200
Free Cash Flow,161345600,161345600,136338700,106904500,122485100